repos:
- repo: local

  hooks:
  - id: pre-commit
    name: Run my tests pre commit
    entry: python 
    language: system
    args: [pre_commit_test.py]

  - id: pre-push
    name: Run my tests pre push
    entry: python 
    language: system
    stages: [push]
    args: [pre-push_test.py]

  - id: post-commit
    name: Run my tests post commit
    entry: python 
    language: system
    stages: [post-commit]
    args: [post_commit_test.py]

  - id: commit-msg
    name: Run my tests commit message
    entry: python 
    language: system
    stages: [commit-msg]
    args: [commit_message_test.py]